INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1001, 'John', 'Doe', 30, 'john.doe@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1002, 'Jane', 'Doe', 25, 'jane.doe@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1003, 'David', 'Smith', 40, 'david.smith@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1004, 'Emily', 'Jones', 35, 'emily.jones@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1005, 'Michael', 'Brown', 28, 'michael.brown@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1006, 'Sarah', 'Davis', 32, 'sarah.davis@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1007, 'Christopher', 'Wilson', 29, 'christopher.wilson@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1008, 'Jessica', 'Miller', 37, 'jessica.miller@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1009, 'Matthew', 'Moore', 26, 'matthew.moore@example.com');
INSERT INTO Customer (id, firstname, lastname, age, email) VALUES (1010, 'Ashley', 'Taylor', 31, 'ashley.taylor@example.com');
INSERT INTO product (id, name, description, price) VALUES (20001, 'Product A', 'Description for Product A', 19.99);
INSERT INTO product (id, name, description, price) VALUES (20002, 'Product B', 'Description for Product B', 29.99);
INSERT INTO product (id, name, description, price) VALUES (20003, 'Product C', 'Description for Product C', 39.99);
INSERT INTO product (id, name, description, price) VALUES (20004, 'Product D', 'Description for Product D', 49.99);
INSERT INTO product (id, name, description, price) VALUES (20005, 'Product E', 'Description for Product E', 59.99);
INSERT INTO product (id, name, description, price) VALUES (20006, 'Product F', 'Description for Product F', 69.99);
INSERT INTO product (id, name, description, price) VALUES (20007, 'Product G', 'Description for Product G', 79.99);
INSERT INTO product (id, name, description, price) VALUES (20008, 'Product H', 'Description for Product H', 89.99);
INSERT INTO product (id, name, description, price) VALUES (20009, 'Product I', 'Description for Product I', 99.99);
INSERT INTO product (id, name, description, price) VALUES (20010, 'Product J', 'Description for Product J', 109.99);
INSERT INTO product (id, name, description, price) VALUES (20011, 'Product K', 'Description for Product K', 119.99);
INSERT INTO product (id, name, description, price) VALUES (20012, 'Product L', 'Description for Product L', 129.99);
INSERT INTO product (id, name, description, price) VALUES (20013, 'Product M', 'Description for Product M', 139.99);
INSERT INTO product (id, name, description, price) VALUES (20014, 'Product N', 'Description for Product N', 149.99);
INSERT INTO product (id, name, description, price) VALUES (20015, 'Product O', 'Description for Product O', 159.99);
INSERT INTO product (id, name, description, price) VALUES (20016, 'Product P', 'Description for Product P', 169.99);
INSERT INTO product (id, name, description, price) VALUES (20017, 'Product Q', 'Description for Product Q', 179.99);
INSERT INTO product (id, name, description, price) VALUES (20018, 'Product R', 'Description for Product R', 189.99);
INSERT INTO product (id, name, description, price) VALUES (20019, 'Product S', 'Description for Product S', 199.99);
INSERT INTO product (id, name, description, price) VALUES (20020, 'Product T', 'Description for Product T', 209.99);